# -*- coding: utf-8 -*-
"""sentiment analysis_nlp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10DxrkWKfwuhDj4GY6K3CPhFGhwpT6-Q_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv("Restaurant_Reviews.tsv",delimiter='\t',quoting=3)

import re
import nltk
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
corpus=[]
ps=PorterStemmer()
for i in range(0,1000):
  review=re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
  review=review.lower()
  review=review.split()
  allstop_words=stopwords.words('english')
  allstop_words.remove('not')
  review=[ps.stem(word) for word in review if not word in set(allstop_words)]
  review=' '.join(review)
  corpus.append(review)

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1500)
X=cv.fit_transform(corpus).toarray()
y=dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,random_state=0)

from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(Xtrain,ytrain)

ypred=classifier.predict(Xtest)
print(np.concatenate(((ypred.reshape(len(ypred),1)),(ytest.reshape(len(ytest),1))),axis=1))